### ISSUE TITLE
Unknown Argument

### ISSUE THREAD

**Issue by Philipp66904** [THI-Drone/mission_software_launch#1]
Whoever is responsible for the `launch.py`, the following lines are not working (unknown argument error):
```python
arguments=['--ros-args', '--log-file', PathJoinSubstitution([log_directory, 'waypoint_node.log'])]
```

Please checkout the whole repository and test your launch file locally before pushing something from ChatGPT without any checks.
Thanks.

**Comment by PhilipDelan** [comment]
removed and fixed
