### ISSUE TITLE
Store the Ros Bag and Logs in a subfolder

### ISSUE THREAD

**Issue by Philipp66904** [THI-Drone/mission_software_launch#2]
Please store your ros bag and logs in a subfolder and not in `/bag` and `/log` directly, as this introduces problems when starting the launch file again in the same container.
Just use a folder with a timestamp folder as child: `bag/2024-05-24T09:13:10` and `log/2024-05-24T09:13:10`

**Comment by Philipp66904** [comment]
@maf0115

**Comment by PhilipDelan** [comment]
added
