### ISSUE TITLE
Use SetEnvironmentVariable

### ISSUE THREAD

**Issue by J0las** [THI-Drone/mission_software_launch#3]
Why not use the SetEnvironmentVariable launch action.
See here: https://github.com/ros2/launch/issues/597
https://github.com/THI-Drone/mission_software_launch/blob/ad531a5f4e05fcc33ec62e3e9bac1d3d7fdc7b5e/launch/launch.py#L42

**Comment by PhilipDelan** [comment]
Using SetEnvironmentVariable can actually be a good option to set environment variables system-wide instead of defining them individually for each node.

**Comment by PhilipDelan** [comment]
changed to environment variables
