### ISSUE TITLE
Remap rosout into namespace

### ISSUE THREAD

**Issue by J0las** [THI-Drone/mission_software_launch#5]
https://github.com/THI-Drone/mission_software_launch/blob/4a82b15e04112d4f7582cd8758bb09321ebc84e3/launch/launch.py#L63
https://github.com/THI-Drone/mission_software_launch/blob/4a82b15e04112d4f7582cd8758bb09321ebc84e3/launch/launch.py#L71
https://github.com/THI-Drone/mission_software_launch/blob/4a82b15e04112d4f7582cd8758bb09321ebc84e3/launch/launch.py#L79
https://github.com/THI-Drone/mission_software_launch/blob/4a82b15e04112d4f7582cd8758bb09321ebc84e3/launch/launch.py#L87

**Comment by PhilipDelan** [comment]
```
remappings=[('/rosout', [namespace, '/rosout'])],
 # arguments=['--ros-args', '--log-level', 'DEBUG']
 ```

**Comment by PhilipDelan** [comment]
Updated launch file for UAV nodes

- Ensured logging is enabled for Waypoint and QR Code scanner nodes.
- Remapped rosout into the namespace for all nodes.
- Maintained debug log level for detailed logging.

Note: This update is untested.
