### ISSUE TITLE
[IMPORTANT] No logs for Waypoint and QR Code scanner node

### ISSUE THREAD

**Issue by Philipp66904** [THI-Drone/mission_software_launch#9]
In many of our flights during flight day 3, the log for the waypoint and qr code scanner node are completely empty.

**Comment by Philipp66904** [comment]
The logs can be found here: https://drive.google.com/drive/folders/1-2gnSmibS07wBIrM6wb0Xbhact38qdht

**Comment by Philipp66904** [comment]
@J0las @J0hn-Lawrence @di-math

**Comment by Philipp66904** [comment]
And is it on purpose that we don't log `DEBUG` messages?

**Comment by J0las** [comment]
> And is it on purpose that we don't log `DEBUG` messages?

No, this can´t be right. We need debug messages in the logs.

**Comment by J0las** [comment]
> The logs can be found here: https://drive.google.com/drive/folders/1-2gnSmibS07wBIrM6wb0Xbhact38qdht

Do you have a specific folder this happened in?

**Comment by J0las** [comment]
At least in the current dev branch, the debug log level setting is commented out:
https://github.com/THI-Drone/mission_software_launch/blob/37fa88a271cfc421fffa6081314fa58014b4f5ab/launch/launch.py#L59

**Comment by J0las** [comment]
Do we need a PR and approve flow here as well?

**Comment by Philipp66904** [comment]
For example this one: https://drive.google.com/drive/folders/1gIfrk5p6EuIPCZ26kYghqS4K3qMkEg5n

**Comment by Philipp66904** [comment]
> Do we need a PR and approve flow here as well?

We had one: https://github.com/THI-Drone/mission_software_launch/pull/7

**Comment by J0las** [comment]
> For example this one: https://drive.google.com/drive/folders/1gIfrk5p6EuIPCZ26kYghqS4K3qMkEg5n

Are we sure this isn´t an scp issue and the files on board are not empty?

**Comment by J0las** [comment]
> > Do we need a PR and approve flow here as well?
> 
> We had one: #7

Yeah, that one shouln´t have been merged

**Comment by Philipp66904** [comment]
> > For example this one: https://drive.google.com/drive/folders/1gIfrk5p6EuIPCZ26kYghqS4K3qMkEg5n
> 
> Are we sure this isn´t an scp issue and the files on board are not empty?

No, we can't be sure about that. But the other files are looking fine and this is a rather consistent issue.

**Comment by J0las** [comment]
> > > For example this one: https://drive.google.com/drive/folders/1gIfrk5p6EuIPCZ26kYghqS4K3qMkEg5n
> > 
> > 
> > Are we sure this isn´t an scp issue and the files on board are not empty?
> 
> No, we can't be sure about that. But the other files are looking fine and this is a rather consistent issue.

I would like to double check that, so that we are not hunting a phantom here while the issue lies somewhere else entirely

**Comment by J0las** [comment]
Does your mdf checker node use ros logs? @Philipp66904
Maybe you can set the env var and try if the log file is created even if there was no recorded log

**Comment by Philipp66904** [comment]
> Does your mdf checker node use ros logs? @Philipp66904
> Maybe you can set the env var and try if the log file is created even if there was no recorded log

No, it doesn't. It's kept completely ROS free and therefore only uses printf. The final error message is inside the exception, though.

**Comment by J0las** [comment]
I just think it is strange why an empty log file would have been created. I would think it will be created upon the first log.
Thats why I think the MDF checker would be a good canidate to test that, because it uses no ros logs

**Comment by PhilipDelan** [comment]
Updated launch file for UAV nodes

- Ensured logging is enabled for Waypoint and QR Code scanner nodes.
- Remapped rosout into the namespace for all nodes.
- Maintained debug log level for detailed logging.

Note: This update is untested.

**Comment by PhilipDelan** [comment]
@incrazyboyy teste vielleicht mal ob die nodes alles starten in der sim

**Comment by Philipp66904** [comment]
> @incrazyboyy teste vielleicht mal ob die nodes alles starten in der sim
> 
> 

Bitte auch die Logs prüfen

**Comment by Philipp66904** [comment]
Tested and seems to work now @PhilipDelan
